# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Clang Format
on:
  push:
    branches:
      - main
    push:
      - "**/*.h"
      - "**/*.cc"
      - ".github/workflows/clang_format.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    path:
      - "**/*.h"
      - "**/*.cc"
      - ".github/workflows/clang_format.yml"

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
            source: './docs'
            clangFormatVersion: 13
